# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ja/Dokumenty/projekty/projekt2/vivado/project_1.srcs/sources_1/bd/hw/ip/hw_axi_gpio_1_0/hw_axi_gpio_1_0.xci
# IP: The module: 'hw_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ja/Dokumenty/projekty/projekt2/vivado/project_1.gen/sources_1/bd/hw/ip/hw_axi_gpio_1_0/hw_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ja/Dokumenty/projekty/projekt2/vivado/project_1.gen/sources_1/bd/hw/ip/hw_axi_gpio_1_0/hw_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ja/Dokumenty/projekty/projekt2/vivado/project_1.gen/sources_1/bd/hw/ip/hw_axi_gpio_1_0/hw_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ja/Dokumenty/projekty/projekt2/vivado/project_1.srcs/sources_1/bd/hw/ip/hw_axi_gpio_1_0/hw_axi_gpio_1_0.xci
# IP: The module: 'hw_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ja/Dokumenty/projekty/projekt2/vivado/project_1.gen/sources_1/bd/hw/ip/hw_axi_gpio_1_0/hw_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ja/Dokumenty/projekty/projekt2/vivado/project_1.gen/sources_1/bd/hw/ip/hw_axi_gpio_1_0/hw_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ja/Dokumenty/projekty/projekt2/vivado/project_1.gen/sources_1/bd/hw/ip/hw_axi_gpio_1_0/hw_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
